# fly.toml app configuration file generated for ecomreactdev on 2023-09-14T21:22:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ecomreactdev"
primary_region = "yyz"

[build]
  image = "hoangloc1511/ecomreactdev:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings_PublishableKey="pk_test_51Nh1l5BYQAopjhAKGQrmQ4MnPROp6o8JtMcUNVfJM07CXJ4RoNgzzCxuLxtu5WnEW7r0RatHGxNGuoqjghjUG0Nn00K1yX6yuy"
  Cloudinary__CloudName="dajjftzch"
  Cloudinary__ApiKey="131853852137617"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
